**Consider the below code to answer further questions:**

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

In [1]:
import numpy as np

In [13]:
list_=['1','2','3','4','5']

In [14]:
list_

['1', '2', '3', '4', '5']

In [15]:
array_list=np.array(object=list_)

In [16]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [17]:
type(list_)

list

In [18]:
type(array_list)

numpy.ndarray

In [19]:
#another method

print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}")

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

In [20]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [21]:
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3. Considering the following changes in the variable, array_list:**

array_list = np.array(object = list_, dtype = int)

**Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.**

In [22]:
array_list = np.array(object = list_, dtype = int)

In [23]:
array_list

array([1, 2, 3, 4, 5])

**Yes, there will be a difference in the data types of the elements in list_ and array_list after setting dtype = int. The elements in list_ will remain as strings, while the elements in array_list will be converted to integers.**

In [24]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


**Consider the below code to answer further questions:**

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [25]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [26]:
num_array = np.array(object = num_list)

In [27]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [28]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

**Q4. Write a code to find the following characteristics of variable, num_array:**
**(i) shape**
**(ii) size**

In [29]:
num_array.shape

(2, 3)

In [30]:
num_array.size

6

**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.**

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [ ]:
zero_matrix=np.zeros((3,3))

In [32]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
zero_matrix.size

9

In [34]:
zero_matrix.shape

(3, 3)

**Q6. Create an identity matrix of shape (5,5) using numpy functions?**

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [35]:
identity_mat=np.eye(5)

In [36]:
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])